services:
  - type: web
    name: data-solution-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000 